MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
ENCODER_ENABLE = yes
LTO_ENABLE = yes
OLED_ENABLE = yes

SWAP_HANDS_ENABLE = no
TAP_DANCE_ENABLE = no
CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes

RGBLIGHT_ENABLE = yes

RGB_MATRIX_ENABLE = no
RGB_MATRIX_DRIVER = ws2812

VIA_ENABLE = no
