git rm -r -f keyboards/0xcb | Out-Null
git rm -r -f keyboards/10bleoledhub | Out-Null
git rm -r -f keyboards/1upkeyboards | Out-Null
git rm -r -f keyboards/25keys | Out-Null
git rm -r -f keyboards/40percentclub | Out-Null
git rm -r -f keyboards/8pack | Out-Null
git rm -r -f keyboards/a_dux | Out-Null
git rm -r -f keyboards/abacus | Out-Null
git rm -r -f keyboards/abstract | Out-Null
git rm -r -f keyboards/acekeyboard | Out-Null
git rm -r -f keyboards/acheron | Out-Null
git rm -r -f keyboards/ada | Out-Null
git rm -r -f keyboards/adkb96 | Out-Null
git rm -r -f keyboards/aeboards | Out-Null
git rm -r -f keyboards/afternoonlabs | Out-Null
git rm -r -f keyboards/ai03 | Out-Null
git rm -r -f keyboards/aidansmithdotdev | Out-Null
git rm -r -f keyboards/aleblazer | Out-Null
git rm -r -f keyboards/alf | Out-Null
git rm -r -f keyboards/alpha | Out-Null
git rm -r -f keyboards/alt34 | Out-Null
git rm -r -f keyboards/amag23 | Out-Null
git rm -r -f keyboards/amjkeyboard | Out-Null
git rm -r -f keyboards/anavi | Out-Null
git rm -r -f keyboards/aos | Out-Null
git rm -r -f keyboards/arabica37 | Out-Null
git rm -r -f keyboards/ares | Out-Null
git rm -r -f keyboards/argyle | Out-Null
git rm -r -f keyboards/arrowmechanics | Out-Null
git rm -r -f keyboards/ask55 | Out-Null
git rm -r -f keyboards/atreus | Out-Null
git rm -r -f keyboards/atxkb | Out-Null
git rm -r -f keyboards/aurora65 | Out-Null
git rm -r -f keyboards/avalanche | Out-Null
git rm -r -f keyboards/aya | Out-Null
git rm -r -f keyboards/bandominedoni | Out-Null
git rm -r -f keyboards/basekeys | Out-Null
git rm -r -f keyboards/bbrfkr | Out-Null
git rm -r -f keyboards/bear_face | Out-Null
git rm -r -f keyboards/beekeeb | Out-Null
git rm -r -f keyboards/bemeier | Out-Null
git rm -r -f keyboards/biacco42 | Out-Null
git rm -r -f keyboards/bioi | Out-Null
git rm -r -f keyboards/blackplum | Out-Null
git rm -r -f keyboards/blank_tehnologii | Out-Null
git rm -r -f keyboards/blockey | Out-Null
git rm -r -f keyboards/bluebell | Out-Null
git rm -r -f keyboards/boardsource | Out-Null
git rm -r -f keyboards/boston | Out-Null
git rm -r -f keyboards/boston_meetup | Out-Null
git rm -r -f keyboards/budgy | Out-Null
git rm -r -f keyboards/buildakb | Out-Null
git rm -r -f keyboards/buzzard | Out-Null
git rm -r -f keyboards/cablecardesigns | Out-Null
git rm -r -f keyboards/cannonkeys | Out-Null
git rm -r -f keyboards/cantor | Out-Null
git rm -r -f keyboards/capsunlocked | Out-Null
git rm -r -f keyboards/catch22 | Out-Null
git rm -r -f keyboards/chalice | Out-Null
git rm -r -f keyboards/charue | Out-Null
git rm -r -f keyboards/checkerboards | Out-Null
git rm -r -f keyboards/cheshire | Out-Null
git rm -r -f keyboards/chew | Out-Null
git rm -r -f keyboards/chlx | Out-Null
git rm -r -f keyboards/cipulot | Out-Null
git rm -r -f keyboards/clickety_split | Out-Null
git rm -r -f keyboards/clueboard | Out-Null
git rm -r -f keyboards/contender | Out-Null
git rm -r -f keyboards/controllerworks | Out-Null
git rm -r -f keyboards/converter | Out-Null
git rm -r -f keyboards/coseyfannitutti | Out-Null
git rm -r -f keyboards/cosmo65 | Out-Null
git rm -r -f keyboards/cozykeys | Out-Null
git rm -r -f keyboards/cradio | Out-Null
git rm -r -f keyboards/craftwalk | Out-Null
git rm -r -f keyboards/crazy_keyboard_68 | Out-Null
git rm -r -f keyboards/custommk | Out-Null
git rm -r -f keyboards/cx60 | Out-Null
git rm -r -f keyboards/dailycraft | Out-Null
git rm -r -f keyboards/db | Out-Null
git rm -r -f keyboards/delikeeb | Out-Null
git rm -r -f keyboards/deltasplit75 | Out-Null
git rm -r -f keyboards/dichotomy | Out-Null
git rm -r -f keyboards/dm9records | Out-Null
git rm -r -f keyboards/dmqdesign | Out-Null
git rm -r -f keyboards/dnworks | Out-Null
git rm -r -f keyboards/do60 | Out-Null
git rm -r -f keyboards/doio | Out-Null
git rm -r -f keyboards/donutcables | Out-Null
git rm -r -f keyboards/doodboard | Out-Null
git rm -r -f keyboards/doppelganger | Out-Null
git rm -r -f keyboards/draculad | Out-Null
git rm -r -f keyboards/draytronics | Out-Null
git rm -r -f keyboards/duck | Out-Null
git rm -r -f keyboards/dumbo | Out-Null
git rm -r -f keyboards/durgod | Out-Null
git rm -r -f keyboards/dyz | Out-Null
git rm -r -f keyboards/dz60 | Out-Null
git rm -r -f keyboards/dztech | Out-Null
git rm -r -f keyboards/ealdin | Out-Null
git rm -r -f keyboards/eason | Out-Null
git rm -r -f keyboards/ebastler | Out-Null
git rm -r -f keyboards/edi | Out-Null
git rm -r -f keyboards/edinburgh41 | Out-Null
git rm -r -f keyboards/eek | Out-Null
git rm -r -f keyboards/ein_60 | Out-Null
git rm -r -f keyboards/elcantorhs | Out-Null
git rm -r -f keyboards/elephant42 | Out-Null
git rm -r -f keyboards/enviousdesign | Out-Null
git rm -r -f keyboards/ep | Out-Null
git rm -r -f keyboards/era | Out-Null
git rm -r -f keyboards/ergodox_ez | Out-Null
git rm -r -f keyboards/ergoslab | Out-Null
git rm -r -f keyboards/ergotravel | Out-Null
git rm -r -f keyboards/esca | Out-Null
git rm -r -f keyboards/eternal_keypad | Out-Null
git rm -r -f keyboards/etiennecollin | Out-Null
git rm -r -f keyboards/evolv | Out-Null
git rm -r -f keyboards/evyd13 | Out-Null
git rm -r -f keyboards/exclusive | Out-Null
git rm -r -f keyboards/exent | Out-Null
git rm -r -f keyboards/eyeohdesigns | Out-Null
git rm -r -f keyboards/fallacy | Out-Null
git rm -r -f keyboards/fatotesa | Out-Null
git rm -r -f keyboards/fc660c | Out-Null
git rm -r -f keyboards/ferris | Out-Null
git rm -r -f keyboards/ffkeebs | Out-Null
git rm -r -f keyboards/fjlabs | Out-Null
git rm -r -f keyboards/fleuron | Out-Null
git rm -r -f keyboards/fluorite | Out-Null
git rm -r -f keyboards/flx | Out-Null
git rm -r -f keyboards/flxlb | Out-Null
git rm -r -f keyboards/for_science | Out-Null
git rm -r -f keyboards/fortitude60 | Out-Null
git rm -r -f keyboards/foxlab | Out-Null
git rm -r -f keyboards/frooastboard | Out-Null
git rm -r -f keyboards/ft | Out-Null
git rm -r -f keyboards/fungo | Out-Null
git rm -r -f keyboards/gami_studio | Out-Null
git rm -r -f keyboards/geekboards | Out-Null
git rm -r -f keyboards/gh60 | Out-Null
git rm -r -f keyboards/ghs | Out-Null
git rm -r -f keyboards/giabalanai | Out-Null
git rm -r -f keyboards/gkeyboard | Out-Null
git rm -r -f keyboards/gl516 | Out-Null
git rm -r -f keyboards/gmmk | Out-Null
git rm -r -f keyboards/gray_studio | Out-Null
git rm -r -f keyboards/gregandcin | Out-Null
git rm -r -f keyboards/hackpad | Out-Null
git rm -r -f keyboards/hadron | Out-Null
git rm -r -f keyboards/halfcliff | Out-Null
git rm -r -f keyboards/halokeys | Out-Null
git rm -r -f keyboards/handwired | Out-Null
git rm -r -f keyboards/hardwareabstraction | Out-Null
git rm -r -f keyboards/heliar | Out-Null
git rm -r -f keyboards/helix | Out-Null
git rm -r -f keyboards/hidtech | Out-Null
git rm -r -f keyboards/hifumi | Out-Null
git rm -r -f keyboards/hillside | Out-Null
git rm -r -f keyboards/hineybush | Out-Null
git rm -r -f keyboards/hnahkb | Out-Null
git rm -r -f keyboards/horrortroll | Out-Null
git rm -r -f keyboards/hotdox76v2 | Out-Null
git rm -r -f keyboards/hp69 | Out-Null
git rm -r -f keyboards/hs60 | Out-Null
git rm -r -f keyboards/hubble | Out-Null
git rm -r -f keyboards/ibm | Out-Null
git rm -r -f keyboards/ibnuda | Out-Null
git rm -r -f keyboards/idank | Out-Null
git rm -r -f keyboards/idb | Out-Null
git rm -r -f keyboards/idobao | Out-Null
git rm -r -f keyboards/ilumkb | Out-Null
git rm -r -f keyboards/inett_studio | Out-Null
git rm -r -f keyboards/input_club | Out-Null
git rm -r -f keyboards/irene | Out-Null
git rm -r -f keyboards/jacky_studio | Out-Null
git rm -r -f keyboards/jae | Out-Null
git rm -r -f keyboards/janus | Out-Null
git rm -r -f keyboards/jd40 | Out-Null
git rm -r -f keyboards/jels | Out-Null
git rm -r -f keyboards/jian | Out-Null
git rm -r -f keyboards/jiran | Out-Null
git rm -r -f keyboards/jkeys_design | Out-Null
git rm -r -f keyboards/jolofsor | Out-Null
git rm -r -f keyboards/jones | Out-Null
git rm -r -f keyboards/jorne | Out-Null
git rm -r -f keyboards/joshajohnson | Out-Null
git rm -r -f keyboards/jukaie | Out-Null
git rm -r -f keyboards/junco | Out-Null
git rm -r -f keyboards/kabedon | Out-Null
git rm -r -f keyboards/kagizaraya | Out-Null
git rm -r -f keyboards/kakunpc | Out-Null
git rm -r -f keyboards/kaly | Out-Null
git rm -r -f keyboards/kapcave | Out-Null
git rm -r -f keyboards/kapl | Out-Null
git rm -r -f keyboards/karn | Out-Null
git rm -r -f keyboards/kb58 | Out-Null
git rm -r -f keyboards/kbdfans | Out-Null
git rm -r -f keyboards/kc60 | Out-Null
git rm -r -f keyboards/kc60se | Out-Null
git rm -r -f keyboards/keaboard | Out-Null
git rm -r -f keyboards/keebformom | Out-Null
git rm -r -f keyboards/keebio | Out-Null
git rm -r -f keyboards/keebmonkey | Out-Null
git rm -r -f keyboards/keebsforall | Out-Null
git rm -r -f keyboards/keebwerk | Out-Null
git rm -r -f keyboards/kegen | Out-Null
git rm -r -f keyboards/keycapsss | Out-Null
git rm -r -f keyboards/keychron | Out-Null
git rm -r -f keyboards/keygem | Out-Null
git rm -r -f keyboards/keyhive | Out-Null
git rm -r -f keyboards/keyprez | Out-Null
git rm -r -f keyboards/keyquest | Out-Null
git rm -r -f keyboards/keysofkings | Out-Null
git rm -r -f keyboards/keystonecaps | Out-Null
git rm -r -f keyboards/kingly_keys | Out-Null
git rm -r -f keyboards/kiwikey | Out-Null
git rm -r -f keyboards/kkatano | Out-Null
git rm -r -f keyboards/kona_classic | Out-Null
git rm -r -f keyboards/kopibeng | Out-Null
git rm -r -f keyboards/kprepublic | Out-Null
git rm -r -f keyboards/kradoindustries | Out-Null
git rm -r -f keyboards/ktec | Out-Null
git rm -r -f keyboards/kumaokobo | Out-Null
git rm -r -f keyboards/latincompass | Out-Null
git rm -r -f keyboards/lazydesigners | Out-Null
git rm -r -f keyboards/lets_split | Out-Null
git rm -r -f keyboards/lfkeyboards | Out-Null
git rm -r -f keyboards/lily58 | Out-Null
git rm -r -f keyboards/lime | Out-Null
git rm -r -f keyboards/linworks | Out-Null
git rm -r -f keyboards/lm_keyboard | Out-Null
git rm -r -f keyboards/longnald | Out-Null
git rm -r -f keyboards/majistic | Out-Null
git rm -r -f keyboards/makeymakey | Out-Null
git rm -r -f keyboards/malevolti | Out-Null
git rm -r -f keyboards/manta60 | Out-Null
git rm -r -f keyboards/maple_computing | Out-Null
git rm -r -f keyboards/mariorion_v25 | Out-Null
git rm -r -f keyboards/marksard | Out-Null
git rm -r -f keyboards/masterworks | Out-Null
git rm -r -f keyboards/matrix | Out-Null
git rm -r -f keyboards/maxr1998 | Out-Null
git rm -r -f keyboards/mc_76k | Out-Null
git rm -r -f keyboards/mechanickeys | Out-Null
git rm -r -f keyboards/mechkeys | Out-Null
git rm -r -f keyboards/mechllama | Out-Null
git rm -r -f keyboards/mechlovin | Out-Null
git rm -r -f keyboards/mechstudio | Out-Null
git rm -r -f keyboards/mechwild | Out-Null
git rm -r -f keyboards/meetlab | Out-Null
git rm -r -f keyboards/mehkee96 | Out-Null
git rm -r -f keyboards/melgeek | Out-Null
git rm -r -f keyboards/meow48 | Out-Null
git rm -r -f keyboards/merge | Out-Null
git rm -r -f keyboards/meson | Out-Null
git rm -r -f keyboards/mincedshon | Out-Null
git rm -r -f keyboards/minimon | Out-Null
git rm -r -f keyboards/mint60 | Out-Null
git rm -r -f keyboards/misonoworks | Out-Null
git rm -r -f keyboards/misterknife | Out-Null
git rm -r -f keyboards/miuni32 | Out-Null
git rm -r -f keyboards/mixi | Out-Null
git rm -r -f keyboards/mk65 | Out-Null
git rm -r -f keyboards/mlego | Out-Null
git rm -r -f keyboards/mode | Out-Null
git rm -r -f keyboards/momoka_ergo | Out-Null
git rm -r -f keyboards/monsgeek | Out-Null
git rm -r -f keyboards/mothwing | Out-Null
git rm -r -f keyboards/mt | Out-Null
git rm -r -f keyboards/mtbkeys | Out-Null
git rm -r -f keyboards/murcielago | Out-Null
git rm -r -f keyboards/mwstudio | Out-Null
git rm -r -f keyboards/mxss | Out-Null
git rm -r -f keyboards/nacly | Out-Null
git rm -r -f keyboards/neito | Out-Null
git rm -r -f keyboards/neokeys | Out-Null
git rm -r -f keyboards/neson_design | Out-Null
git rm -r -f keyboards/newgame40 | Out-Null
git rm -r -f keyboards/nightly_boards | Out-Null
git rm -r -f keyboards/nix_studio | Out-Null
git rm -r -f keyboards/novelkeys | Out-Null
git rm -r -f keyboards/noxary | Out-Null
git rm -r -f keyboards/nullbitsco | Out-Null
git rm -r -f keyboards/obosob | Out-Null
git rm -r -f keyboards/ogre | Out-Null
git rm -r -f keyboards/ok60 | Out-Null
git rm -r -f keyboards/om60 | Out-Null
git rm -r -f keyboards/omkbd | Out-Null
git rm -r -f keyboards/omnikeyish | Out-Null
git rm -r -f keyboards/opendeck | Out-Null
git rm -r -f keyboards/ortho5by12 | Out-Null
git rm -r -f keyboards/orthocode | Out-Null
git rm -r -f keyboards/orthodox | Out-Null
git rm -r -f keyboards/orthograph | Out-Null
git rm -r -f keyboards/owlab | Out-Null
git rm -r -f keyboards/p3d | Out-Null
git rm -r -f keyboards/panc40 | Out-Null
git rm -r -f keyboards/pauperboards | Out-Null
git rm -r -f keyboards/pearl | Out-Null
git rm -r -f keyboards/pearlboards | Out-Null
git rm -r -f keyboards/percent | Out-Null
git rm -r -f keyboards/phantom | Out-Null
git rm -r -f keyboards/phase_studio | Out-Null
git rm -r -f keyboards/phoenix | Out-Null
git rm -r -f keyboards/pica40 | Out-Null
git rm -r -f keyboards/picolab | Out-Null
git rm -r -f keyboards/pimentoso | Out-Null
git rm -r -f keyboards/pinky | Out-Null
git rm -r -f keyboards/pisces | Out-Null
git rm -r -f keyboards/pixelspace | Out-Null
git rm -r -f keyboards/planck | Out-Null
git rm -r -f keyboards/playkbtw | Out-Null
git rm -r -f keyboards/ploopyco | Out-Null
git rm -r -f keyboards/pluckey | Out-Null
git rm -r -f keyboards/plut0nium | Out-Null
git rm -r -f keyboards/plywrks | Out-Null
git rm -r -f keyboards/pmk | Out-Null
git rm -r -f keyboards/poker87c | Out-Null
git rm -r -f keyboards/poker87d | Out-Null
git rm -r -f keyboards/polycarbdiet | Out-Null
git rm -r -f keyboards/pom_keyboards | Out-Null
git rm -r -f keyboards/printedpad | Out-Null
git rm -r -f keyboards/program_yoink | Out-Null
git rm -r -f keyboards/projectd | Out-Null
git rm -r -f keyboards/projectkb | Out-Null
git rm -r -f keyboards/proteus67 | Out-Null
git rm -r -f keyboards/prototypist | Out-Null
git rm -r -f keyboards/pteron36 | Out-Null
git rm -r -f keyboards/punk75 | Out-Null
git rm -r -f keyboards/quad_h | Out-Null
git rm -r -f keyboards/quarkeys | Out-Null
git rm -r -f keyboards/quokka | Out-Null
git rm -r -f keyboards/qvex | Out-Null
git rm -r -f keyboards/qwertykeys | Out-Null
git rm -r -f keyboards/qwertyydox | Out-Null
git rm -r -f keyboards/rainkeebs | Out-Null
git rm -r -f keyboards/rart | Out-Null
git rm -r -f keyboards/rastersoft | Out-Null
git rm -r -f keyboards/rate | Out-Null
git rm -r -f keyboards/recompile_keys | Out-Null
git rm -r -f keyboards/rect44 | Out-Null
git rm -r -f keyboards/redox | Out-Null
git rm -r -f keyboards/redox_media | Out-Null
git rm -r -f keyboards/redscarf_i | Out-Null
git rm -r -f keyboards/reedskeebs | Out-Null
git rm -r -f keyboards/retro_75 | Out-Null
git rm -r -f keyboards/reversestudio | Out-Null
git rm -r -f keyboards/reviung | Out-Null
git rm -r -f keyboards/rgbkb | Out-Null
git rm -r -f keyboards/rico | Out-Null
git rm -r -f keyboards/rkg68 | Out-Null
git rm -r -f keyboards/rmi_kb | Out-Null
git rm -r -f keyboards/rocketboard_16 | Out-Null
git rm -r -f keyboards/rubi | Out-Null
git rm -r -f keyboards/runes | Out-Null
git rm -r -f keyboards/rura66 | Out-Null
git rm -r -f keyboards/ryloo_studio | Out-Null
git rm -r -f keyboards/salicylic_acid3 | Out-Null
git rm -r -f keyboards/sam | Out-Null
git rm -r -f keyboards/sawnsprojects | Out-Null
git rm -r -f keyboards/scatter42 | Out-Null
git rm -r -f keyboards/sck | Out-Null
git rm -r -f keyboards/sekigon | Out-Null
git rm -r -f keyboards/sendyyeah | Out-Null
git rm -r -f keyboards/senselessclay | Out-Null
git rm -r -f keyboards/sentraq | Out-Null
git rm -r -f keyboards/sets3n | Out-Null
git rm -r -f keyboards/sha | Out-Null
git rm -r -f keyboards/shandoncodes | Out-Null
git rm -r -f keyboards/silverbullet44 | Out-Null
git rm -r -f keyboards/sirius | Out-Null
git rm -r -f keyboards/skeletn87 | Out-Null
git rm -r -f keyboards/skippys_custom_pcs | Out-Null
git rm -r -f keyboards/sleepy_craft_studios | Out-Null
git rm -r -f keyboards/smk60 | Out-Null
git rm -r -f keyboards/smoll | Out-Null
git rm -r -f keyboards/sneakbox | Out-Null
git rm -r -f keyboards/snes_macropad | Out-Null
git rm -r -f keyboards/soda | Out-Null
git rm -r -f keyboards/sofle_choc | Out-Null
git rm -r -f keyboards/sowbug | Out-Null
git rm -r -f keyboards/spaceholdings | Out-Null
git rm -r -f keyboards/spacetime | Out-Null
git rm -r -f keyboards/sparrow62 | Out-Null
git rm -r -f keyboards/spleeb | Out-Null
git rm -r -f keyboards/split67 | Out-Null
git rm -r -f keyboards/splitkb | Out-Null
git rm -r -f keyboards/star75 | Out-Null
git rm -r -f keyboards/stello65 | Out-Null
git rm -r -f keyboards/stront | Out-Null
git rm -r -f keyboards/studiokestra | Out-Null
git rm -r -f keyboards/supersplit | Out-Null
git rm -r -f keyboards/switchplate | Out-Null
git rm -r -f keyboards/system76 | Out-Null
git rm -r -f keyboards/tada68 | Out-Null
git rm -r -f keyboards/takashicompany | Out-Null
git rm -r -f keyboards/takashiski | Out-Null
git rm -r -f keyboards/taleguers | Out-Null
git rm -r -f keyboards/tau4 | Out-Null
git rm -r -f keyboards/team0110 | Out-Null
git rm -r -f keyboards/tenki | Out-Null
git rm -r -f keyboards/terrazzo | Out-Null
git rm -r -f keyboards/tgr | Out-Null
git rm -r -f keyboards/the_royal | Out-Null
git rm -r -f keyboards/themadnoodle | Out-Null
git rm -r -f keyboards/tkc | Out-Null
git rm -r -f keyboards/tkw | Out-Null
git rm -r -f keyboards/tmo50 | Out-Null
git rm -r -f keyboards/toffee_studio | Out-Null
git rm -r -f keyboards/tokyokeyboard | Out-Null
git rm -r -f keyboards/tominabox1 | Out-Null
git rm -r -f keyboards/tr60w | Out-Null
git rm -r -f keyboards/trkeyboards | Out-Null
git rm -r -f keyboards/tszaboo | Out-Null
git rm -r -f keyboards/tunks | Out-Null
git rm -r -f keyboards/tweetydabird | Out-Null
git rm -r -f keyboards/tzarc | Out-Null
git rm -r -f keyboards/uk78 | Out-Null
git rm -r -f keyboards/unicomp | Out-Null
git rm -r -f keyboards/unikeyboard | Out-Null
git rm -r -f keyboards/uzu42 | Out-Null
git rm -r -f keyboards/vertex | Out-Null
git rm -r -f keyboards/viktus | Out-Null
git rm -r -f keyboards/vinhcatba | Out-Null
git rm -r -f keyboards/vitamins_included | Out-Null
git rm -r -f keyboards/waldo | Out-Null
git rm -r -f keyboards/walletburner | Out-Null
git rm -r -f keyboards/waterfowl | Out-Null
git rm -r -f keyboards/wavtype | Out-Null
git rm -r -f keyboards/westfoxtrot | Out-Null
git rm -r -f keyboards/westm | Out-Null
git rm -r -f keyboards/whitefacemountain | Out-Null
git rm -r -f keyboards/wilba_tech | Out-Null
git rm -r -f keyboards/winkeyless | Out-Null
git rm -r -f keyboards/winry | Out-Null
git rm -r -f keyboards/wolf | Out-Null
git rm -r -f keyboards/wolfmarkclub | Out-Null
git rm -r -f keyboards/woodkeys | Out-Null
git rm -r -f keyboards/work_louder | Out-Null
git rm -r -f keyboards/wsk | Out-Null
git rm -r -f keyboards/wuque | Out-Null
git rm -r -f keyboards/xelus | Out-Null
git rm -r -f keyboards/xenon | Out-Null
git rm -r -f keyboards/xiudi | Out-Null
git rm -r -f keyboards/yampad | Out-Null
git rm -r -f keyboards/yandrstudio | Out-Null
git rm -r -f keyboards/yanghu | Out-Null
git rm -r -f keyboards/yeehaw | Out-Null
git rm -r -f keyboards/yiancardesigns | Out-Null
git rm -r -f keyboards/ymdk | Out-Null
git rm -r -f keyboards/yoichiro | Out-Null
git rm -r -f keyboards/yosino58 | Out-Null
git rm -r -f keyboards/yushakobo | Out-Null
git rm -r -f keyboards/yynmt | Out-Null
git rm -r -f keyboards/zigotica | Out-Null
git rm -r -f keyboards/ziptyze | Out-Null
git rm -r -f keyboards/zj68 | Out-Null
git rm -r -f keyboards/zlabkeeb | Out-Null
git rm -r -f keyboards/zlant | Out-Null
git rm -r -f keyboards/zoo | Out-Null
git rm -r -f keyboards/zsa | Out-Null
git rm -r -f keyboards/zvecr | Out-Null
