MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
ENCODER_ENABLE = yes
LTO_ENABLE = yes
OLED_ENABLE = yes

TAP_DANCE_ENABLE = no

RGBLIGHT_ENABLE = yes

RGB_MATRIX_ENABLE = no
RGB_MATRIX_DRIVER = ws2812

VIA_ENABLE = no
